platform :ios, '7.0'

target "MNiang" do

pod 'AFNetworking', "~> 2.5.4"
pod 'MBProgressHUD', "~> 0.9.1"
pod 'SDWebImage', "~> 3.7.3"
pod 'Masonry', "~> 0.6.2"
pod 'CTAssetsPickerController',"~> 2.9.5"

end
